-- ============================================
-- Supabase Schema Setup - E-commerce Platform
-- ============================================

-- Step 1: Create Tables
-- ============================================

-- Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  category_id BIGINT REFERENCES categories(id),
  stock INTEGER DEFAULT 0
);

-- Create Shipping Zones (Wilayas)
CREATE TABLE IF NOT EXISTS shipping_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wilaya_code INTEGER NOT NULL UNIQUE,
  wilaya_name TEXT NOT NULL,
  home_delivery_price NUMERIC DEFAULT 0,
  desk_delivery_price NUMERIC DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  customer_info JSONB NOT NULL, -- { name, phone, address, wilaya, commune }
  items JSONB NOT NULL, -- [{ product_id, quantity, price, title }]
  total_amount NUMERIC NOT NULL,
  shipping_cost NUMERIC NOT NULL,
  delivery_type TEXT NOT NULL, -- 'home' | 'desk'
  status TEXT DEFAULT 'pending', -- pending, confirmed, shipped, cancelled
  pixel_id TEXT -- For tracking which pixel event triggered this if needed
);

-- Step 2: Enable RLS (Row Level Security)
-- ============================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Step 3: Drop Existing Policies (to avoid conflicts)
-- ============================================

-- Products Policies
DROP POLICY IF EXISTS "Public Products Request" ON products;
DROP POLICY IF EXISTS "Admin Products Control" ON products;
DROP POLICY IF EXISTS "Enable read access for all users" ON products;
DROP POLICY IF EXISTS "Enable insert for all users" ON products;
DROP POLICY IF EXISTS "Enable update for all users" ON products;
DROP POLICY IF EXISTS "Enable delete for all users" ON products;

-- Categories Policies
DROP POLICY IF EXISTS "Public Categories Request" ON categories;
DROP POLICY IF EXISTS "Admin Categories Control" ON categories;
DROP POLICY IF EXISTS "Enable read access for all users" ON categories;
DROP POLICY IF EXISTS "Enable insert for all users" ON categories;

-- Shipping Zones Policies
DROP POLICY IF EXISTS "Public Shipping Request" ON shipping_zones;
DROP POLICY IF EXISTS "Admin Shipping Control" ON shipping_zones;
DROP POLICY IF EXISTS "Enable read access for all users" ON shipping_zones;
DROP POLICY IF EXISTS "Enable insert for all users" ON shipping_zones;

-- Orders Policies
DROP POLICY IF EXISTS "Public Place Order" ON orders;
DROP POLICY IF EXISTS "Admin Manage Orders" ON orders;
DROP POLICY IF EXISTS "Admin Update Orders" ON orders;
DROP POLICY IF EXISTS "Enable read access for all users" ON orders;
DROP POLICY IF EXISTS "Enable insert for all users" ON orders;
DROP POLICY IF EXISTS "Enable update for all users" ON orders;

-- Step 4: Create New Policies (Public Access for Development)
-- ============================================

-- Products: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON products
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON products
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON products
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON products
  FOR DELETE USING (true);

-- Categories: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON categories
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON categories
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON categories
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON categories
  FOR DELETE USING (true);

-- Shipping Zones: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON shipping_zones
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON shipping_zones
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON shipping_zones
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON shipping_zones
  FOR DELETE USING (true);

-- Orders: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON orders
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON orders
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON orders
  FOR DELETE USING (true);

-- Step 5: Storage Setup
-- ============================================

-- Create 'products' bucket (if not exists)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'products',
  'products',
  true,
  5242880, -- 5MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif'];

-- Drop existing storage policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;
DROP POLICY IF EXISTS "Auth Update/Delete" ON storage.objects;
DROP POLICY IF EXISTS "Enable read access for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable insert for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable update for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable delete for all users" ON storage.objects;

-- Create storage policies for 'products' bucket
CREATE POLICY "Enable read access for all users" ON storage.objects
  FOR SELECT USING (bucket_id = 'products');

CREATE POLICY "Enable insert for all users" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'products');

CREATE POLICY "Enable update for all users" ON storage.objects
  FOR UPDATE USING (bucket_id = 'products');

CREATE POLICY "Enable delete for all users" ON storage.objects
  FOR DELETE USING (bucket_id = 'products');

-- ============================================
-- Setup Complete!
-- ============================================
-- All tables, policies, and storage are now configured
-- You can now add products without RLS errors
