-- Create Categories Table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text unique not null
);

-- Create Products Table
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text unique not null,
  description text,
  price numeric not null,
  images text[] default array[]::text[],
  category_id bigint references categories(id),
  stock integer default 0
);

-- Create Shipping Zones (Wilayas)
create table if not exists shipping_zones (
  id bigint generated by default as identity primary key,
  wilaya_code integer not null unique,
  wilaya_name text not null,
  home_delivery_price numeric default 0,
  desk_delivery_price numeric default 0,
  is_active boolean default true
);

-- Create Orders Table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_info jsonb not null, -- { name, phone, address, wilaya, commune }
  items jsonb not null, -- [{ product_id, quantity, price, title }]
  total_amount numeric not null,
  shipping_cost numeric not null,
  delivery_type text not null, -- 'home' | 'desk'
  status text default 'pending', -- pending, confirmed, shipped, cancelled
  pixel_id text -- For tracking which pixel event triggered this if needed
);

-- Enable RLS (Row Level Security)
alter table products enable row level security;
alter table categories enable row level security;
alter table shipping_zones enable row level security;
alter table orders enable row level security;

-- Policies (Drop first to avoid 'policy already exists' error)

-- Products
drop policy if exists "Public Products Request" on products;
create policy "Public Products Request" on products for select using (true);

drop policy if exists "Admin Products Control" on products;
create policy "Admin Products Control" on products for all using (auth.role() = 'authenticated');

-- Categories
drop policy if exists "Public Categories Request" on categories;
create policy "Public Categories Request" on categories for select using (true);

drop policy if exists "Admin Categories Control" on categories;
create policy "Admin Categories Control" on categories for all using (auth.role() = 'authenticated');

-- Shipping Zones
drop policy if exists "Public Shipping Request" on shipping_zones;
create policy "Public Shipping Request" on shipping_zones for select using (true);

drop policy if exists "Admin Shipping Control" on shipping_zones;
create policy "Admin Shipping Control" on shipping_zones for all using (auth.role() = 'authenticated');

-- Orders
drop policy if exists "Public Place Order" on orders;
create policy "Public Place Order" on orders for insert with check (true);

drop policy if exists "Admin Manage Orders" on orders;
create policy "Admin Manage Orders" on orders for select using (auth.role() = 'authenticated');

drop policy if exists "Admin Update Orders" on orders;
create policy "Admin Update Orders" on orders for update using (auth.role() = 'authenticated');

-- STORAGE: Create 'products' bucket and policies
insert into storage.buckets (id, name, public) values ('products', 'products', true)
on conflict (id) do nothing;

-- Storage Policies
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using ( bucket_id = 'products' );

drop policy if exists "Auth Upload" on storage.objects;
create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'products' and auth.role() = 'authenticated' );

drop policy if exists "Auth Update/Delete" on storage.objects;
create policy "Auth Update/Delete" on storage.objects for all using ( bucket_id = 'products' and auth.role() = 'authenticated' );
