-- ============================================
-- Supabase Schema Setup - E-commerce Platform
-- ============================================

-- Step 1: Create Tables
-- ============================================

-- Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  sale_price NUMERIC,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  category_id BIGINT REFERENCES categories(id),
  stock INTEGER DEFAULT 0,
  in_stock BOOLEAN DEFAULT TRUE
);

-- Create Shipping Zones (Wilayas)
CREATE TABLE IF NOT EXISTS shipping_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wilaya_code INTEGER NOT NULL UNIQUE,
  wilaya_name TEXT NOT NULL,
  home_delivery_price NUMERIC DEFAULT 0,
  desk_delivery_price NUMERIC DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  customer_info JSONB NOT NULL, -- { name, phone, address, wilaya, commune }
  items JSONB NOT NULL, -- [{ product_id, quantity, price, title }]
  total_amount NUMERIC NOT NULL,
  shipping_cost NUMERIC NOT NULL,
  delivery_type TEXT NOT NULL, -- 'home' | 'desk'
  status TEXT DEFAULT 'new', -- new, confirmed, shipping, delivered, cancelled, returned
  pixel_id TEXT -- For tracking which pixel event triggered this if needed
);

-- Create Settings Table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Step 2: Seed Shipping Zones (58 Algerian Wilayas)
-- ============================================

INSERT INTO shipping_zones (wilaya_code, wilaya_name, home_delivery_price, desk_delivery_price, is_active)
VALUES
  (1, 'Adrar', 800, 600, true),
  (2, 'Chlef', 600, 400, true),
  (3, 'Laghouat', 700, 500, true),
  (4, 'Oum El Bouaghi', 600, 400, true),
  (5, 'Batna', 600, 400, true),
  (6, 'Béjaïa', 500, 350, true),
  (7, 'Biskra', 650, 450, true),
  (8, 'Béchar', 850, 650, true),
  (9, 'Blida', 400, 300, true),
  (10, 'Bouira', 500, 350, true),
  (11, 'Tamanrasset', 1200, 1000, true),
  (12, 'Tébessa', 700, 500, true),
  (13, 'Tlemcen', 650, 450, true),
  (14, 'Tiaret', 600, 400, true),
  (15, 'Tizi Ouzou', 500, 350, true),
  (16, 'Algiers', 400, 300, true),
  (17, 'Djelfa', 650, 450, true),
  (18, 'Jijel', 550, 400, true),
  (19, 'Sétif', 550, 400, true),
  (20, 'Saïda', 650, 450, true),
  (21, 'Skikda', 600, 400, true),
  (22, 'Sidi Bel Abbès', 650, 450, true),
  (23, 'Annaba', 600, 400, true),
  (24, 'Guelma', 600, 400, true),
  (25, 'Constantine', 550, 400, true),
  (26, 'Médéa', 500, 350, true),
  (27, 'Mostaganem', 600, 400, true),
  (28, 'M''Sila', 600, 450, true),
  (29, 'Mascara', 650, 450, true),
  (30, 'Ouargla', 750, 550, true),
  (31, 'Oran', 500, 350, true),
  (32, 'El Bayadh', 750, 550, true),
  (33, 'Illizi', 1100, 900, true),
  (34, 'Bordj Bou Arréridj', 550, 400, true),
  (35, 'Boumerdès', 450, 300, true),
  (36, 'El Tarf', 650, 450, true),
  (37, 'Tindouf', 1200, 1000, true),
  (38, 'Tissemsilt', 600, 400, true),
  (39, 'El Oued', 700, 500, true),
  (40, 'Khenchela', 650, 450, true),
  (41, 'Souk Ahras', 650, 450, true),
  (42, 'Tipaza', 450, 300, true),
  (43, 'Mila', 600, 400, true),
  (44, 'Aïn Defla', 550, 400, true),
  (45, 'Naâma', 800, 600, true),
  (46, 'Aïn Témouchent', 600, 400, true),
  (47, 'Ghardaïa', 750, 550, true),
  (48, 'Relizane', 600, 400, true),
  (49, 'Timimoun', 900, 700, true),
  (50, 'Bordj Badji Mokhtar', 1300, 1100, true),
  (51, 'Ouled Djellal', 700, 500, true),
  (52, 'Béni Abbès', 950, 750, true),
  (53, 'In Salah', 1000, 800, true),
  (54, 'In Guezzam', 1400, 1200, true),
  (55, 'Touggourt', 750, 550, true),
  (56, 'Djanet', 1150, 950, true),
  (57, 'El M''Ghair', 750, 550, true),
  (58, 'El Meniaa', 800, 600, true)
ON CONFLICT (wilaya_code) DO NOTHING;

-- Step 3: Enable RLS (Row Level Security)
-- ============================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Step 3: Drop Existing Policies (to avoid conflicts)
-- ============================================

-- Products Policies
DROP POLICY IF EXISTS "Public Products Request" ON products;
DROP POLICY IF EXISTS "Admin Products Control" ON products;
DROP POLICY IF EXISTS "Enable read access for all users" ON products;
DROP POLICY IF EXISTS "Enable insert for all users" ON products;
DROP POLICY IF EXISTS "Enable update for all users" ON products;
DROP POLICY IF EXISTS "Enable delete for all users" ON products;

-- Categories Policies
DROP POLICY IF EXISTS "Public Categories Request" ON categories;
DROP POLICY IF EXISTS "Admin Categories Control" ON categories;
DROP POLICY IF EXISTS "Enable read access for all users" ON categories;
DROP POLICY IF EXISTS "Enable insert for all users" ON categories;

-- Shipping Zones Policies
DROP POLICY IF EXISTS "Public Shipping Request" ON shipping_zones;
DROP POLICY IF EXISTS "Admin Shipping Control" ON shipping_zones;
DROP POLICY IF EXISTS "Enable read access for all users" ON shipping_zones;
DROP POLICY IF EXISTS "Enable insert for all users" ON shipping_zones;

-- Orders Policies
DROP POLICY IF EXISTS "Public Place Order" ON orders;
DROP POLICY IF EXISTS "Admin Manage Orders" ON orders;
DROP POLICY IF EXISTS "Admin Update Orders" ON orders;
DROP POLICY IF EXISTS "Enable read access for all users" ON orders;
DROP POLICY IF EXISTS "Enable insert for all users" ON orders;
DROP POLICY IF EXISTS "Enable update for all users" ON orders;

-- Step 4: Create New Policies (Public Access for Development)
-- ============================================

-- Products: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON products
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON products
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON products
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON products
  FOR DELETE USING (true);

-- Categories: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON categories
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON categories
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON categories
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON categories
  FOR DELETE USING (true);

-- Shipping Zones: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON shipping_zones
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON shipping_zones
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON shipping_zones
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON shipping_zones
  FOR DELETE USING (true);

-- Orders: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON orders
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON orders
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON orders
  FOR DELETE USING (true);

-- Settings: Allow ALL operations for everyone
CREATE POLICY "Enable read access for all users" ON settings
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON settings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON settings
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON settings
  FOR DELETE USING (true);

-- Step 5: Storage Setup
-- ============================================

-- Create 'products' bucket (if not exists)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'products',
  'products',
  true,
  5242880, -- 5MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif'];

-- Drop existing storage policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;
DROP POLICY IF EXISTS "Auth Update/Delete" ON storage.objects;
DROP POLICY IF EXISTS "Enable read access for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable insert for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable update for all users" ON storage.objects;
DROP POLICY IF EXISTS "Enable delete for all users" ON storage.objects;

-- Create storage policies for 'products' bucket
CREATE POLICY "Enable read access for all users" ON storage.objects
  FOR SELECT USING (bucket_id = 'products');

CREATE POLICY "Enable insert for all users" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'products');

CREATE POLICY "Enable update for all users" ON storage.objects
  FOR UPDATE USING (bucket_id = 'products');

CREATE POLICY "Enable delete for all users" ON storage.objects
  FOR DELETE USING (bucket_id = 'products');

-- ============================================
-- Setup Complete!
-- ============================================
-- All tables, policies, and storage are now configured
-- You can now add products without RLS errors
